name: wfcache CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  tests:
    name: Test
    runs-on: ubuntu-latest
    steps:
      # Check out the repo
      - uses: actions/checkout@v2
      # Launch Redis in bg
      - name: Launch Redis
        uses: supercharge/redis-github-action@1.2.0
        with:
          redis-version: latest
      # Launch dynamodb local in bg
      - name: Launch DynamoDB Local
        uses: rrainn/dynamodb-action@v2.0.0
        with:
          port: 8000
      # Install go
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.3'
      # Utilize go.mod cache
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      # Run tests
      - run: make test
